development:
  url: <%= ENV["MY_APP_DATABASE_URL"] %>
  adapter: postgresql
  encoding: unicode
  database: work
  username: render_deploy
  password: <%= "RENDER_DEPLOY_DATABASE_PASSWORD" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: work
  username: render_deploy
  password: <%= "RENDER_DEPLOY_DATABASE_PASSWORD" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>

production:
  adapter: postgresql
  encoding: unicode
  database: work
  username: render_deploy
  password: <%= "RENDER_DEPLOY_DATABASE_PASSWORD" %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>

cucumber:
  <<: *TEST